fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run black mol_classifier
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake mol_classifier
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort mol_classifier
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: poetry run mypy mol_classifier
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
    -   id: flake8
        name: Flake8
        entry: poetry run flake8 mol_classifier
        pass_filenames: false
        language: system
